akademia/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from akademia.views import IndexView


admin.autodiscover()

urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^news/', include('news.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^account/', include('ksp_login.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

events/urls.py
from django.conf.urls import include, url

from events.views import (ArchiveView, EventDetailView, AttendanceView,
        latest_event_detail)
from polls.views import EventPollView, EventPollResultsView


urlpatterns = [
    url(r'^$', latest_event_detail, name="event_latest"),
    url(r'^archive/$', ArchiveView.as_view(), name="event_archive"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        EventDetailView.as_view(), kwargs={'slug': ''},
        name="event_detail"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/attendance/$',
        AttendanceView.as_view(), kwargs={'slug': ''},
        name="event_attendance"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/poll/$',
        EventPollView.as_view(), kwargs={'slug': ''},
        name="event_poll"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/poll/results/$',
        EventPollResultsView.as_view(), kwargs={'slug': ''},
        name="event_poll_results"),
]

news/urls.py
from django.conf.urls import include, url

from news.views import EntryListView
from news.feeds import NewsFeed


urlpatterns = [
    url(r'^page/(?P<page>[0-9]+)/$', EntryListView.as_view(),
        name='news_list'),
    url(r'^feed/$', NewsFeed(), name='news_feed'),
]

events/models.py
# coding: utf-8
from __future__ import unicode_literals

import datetime
import os.path
from collections import OrderedDict

from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now

from events.utils import slugify


# In which grade does a high school student graduate?
GRADUATION_GRADE = 4


@python_2_unicode_compatible
class School(models.Model):
    abbreviation = models.CharField(max_length=100,
                                    blank=True,
                                    verbose_name="skratka",
                                    help_text="Sktatka názvu školy.")
    verbose_name = models.CharField(max_length=100,
                                    verbose_name="celý názov")
    addr_name = models.CharField(max_length=100, blank=True)
    street = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=10, blank=True)

    class Meta:
        verbose_name = "škola"
        verbose_name_plural = "školy"
        ordering = ("city", "street", "verbose_name")

    def __str__(self):
        result = ""
        if self.abbreviation:
            result += self.abbreviation + ", "
        result += self.verbose_name
        if self.street:
            result += ", " + self.street
        if self.city or self.zip_code:
            result += ", "
        if self.zip_code:
            result += self.zip_code
        if self.city:
            result += " " + self.city
        return result


@python_2_unicode_compatible
class AdditionalUserDetails(models.Model):
    user = models.OneToOneField('auth.User',
                                related_name='additional_events_details')
    school = models.ForeignKey(School, default=1, verbose_name="škola",
                               help_text='Do políčka napíšte skratku, '
                               'časť názvu alebo adresy školy a následne '
                               'vyberte správnu možnosť zo zoznamu. '
                               'Pokiaľ vaša škola nie je '
                               'v&nbsp;zozname, vyberte "Gymnázium iné" '
                               'a&nbsp;pošlite nám e-mail.')
    is_teacher = models.BooleanField(verbose_name="som učiteľ",
                                     help_text='Učitelia vedia hromadne '
                                     'prihlasovať školy na akcie.')
    graduation = models.IntegerField(blank=True, null=True,
                                     verbose_name="rok maturity",
                                     help_text="Povinné pre žiakov.")
    want_news = models.BooleanField(verbose_name="pozvánky e-mailom",
                                    help_text="Mám záujem dostávať "
                                    "e-mailom pozvánky na ďalšie akcie.")

    class Meta:
        verbose_name = "dodatočné údaje o užívateľoch"
        verbose_name_plural = "dodatočné údaje o užívateľoch"

    def __str__(self):
        return "%s" % (self.user,)

    def get_grade(self, date=None):
        """
        Returns the school grade based on graduation_year and the provided
        date. If no date is provided, today is used.
        """
        if self.graduation is None:
            return None
        if date is None:
            date = datetime.date.today()
        # Normalize the given date's year to the one in which the closest
        # following graduation happens.
        # For simplicity, we assume graduation happens every year on the
        # first day of July.
        if date.month >= 7:
            date = date.replace(year=date.year + 1)
        years_to_graduation = self.graduation - date.year
        return GRADUATION_GRADE - years_to_graduation


def choose_invitation_filename(instance, original):
    return "%s/invitation-%s.pdf" % (instance.date.isoformat(),
                                     slugify(unicode(instance))[:74])


@python_2_unicode_compatible
class Event(models.Model):
    name = models.CharField(max_length=100,
                            help_text="Názov akcie, napr. Klub Trojstenu "
                            "po Náboji FKS")
    date = models.DateField(unique=True)
    deadline = models.DateTimeField(help_text="Deadline na prihlasovanie")
    invitation = models.FileField(upload_to=choose_invitation_filename,
                                  blank=True,
                                  help_text="PDF s pozvánkou, keď bude "
                                  "hotová.")
    sites = models.ManyToManyField(Site)
    poll_begin = models.DateTimeField(blank=True, null=True,
                                      help_text="Spustenie ankety")
    poll_end = models.DateTimeField(blank=True, null=True,
                                    help_text="Ukončenie ankety")
    poll = models.ForeignKey('polls.Poll', blank=True, null=True,
                             related_name="events",
                             help_text="Anketa")

    class Meta:
        verbose_name = "akcia"
        verbose_name_plural = "akcie"
        ordering = ("-date",)

    def __str__(self):
        return "%s %s" % (self.name, self.date.year)

    @models.permalink
    def get_absolute_url(self):
        # We need to check if the event is the latest for this page and we
        # don't have access to the request to just call get_latest_event.
        if Event.objects.filter(sites__id__in=self.sites.all(),
                               date__gt=self.date).count() > 0:
            # There are newer relevant events, generate a general URL.
            return ("event_detail", (), {
                        'year': self.date.strftime('%Y'),
                        'month': self.date.strftime('%m'),
                        'day': self.date.strftime('%d'),
                    })
        # Else just return the link to the latest event.
        return ("event_latest",)

    @models.permalink
    def get_attendance_url(self):
        return ("event_attendance", (), {
                    'year': self.date.strftime('%Y'),
                    'month': self.date.strftime('%m'),
                    'day': self.date.strftime('%d'),
                })

    @models.permalink
    def get_poll_url(self):
        return ("event_poll", (), {
                    'year': self.date.strftime('%Y'),
                    'month': self.date.strftime('%m'),
                    'day': self.date.strftime('%d'),
                })

    @models.permalink
    def get_poll_results_url(self):
        return ("event_poll_results", (), {
                    'year': self.date.strftime('%Y'),
                    'month': self.date.strftime('%m'),
                    'day': self.date.strftime('%d'),
                })

    def get_grouped_lectures(self):
        """
        Returns the lectures for this event in an OrderedDict mapping
        times to lists of lectures sorted by their rooms.
        """
        try:
            return self._grouped_lectures_cache
        except AttributeError:
            result = OrderedDict()
            for lecture in self.lectures.order_by("time", "room"):
                result.setdefault(lecture.time, []).append(lecture)
            self._grouped_lectures_cache = result
            return result

    def is_in_future(self):
        return now().date() <= self.date

    def signup_period_open(self):
        return now() < self.deadline

    def poll_is_active(self):
        now_ = now()
        return (self.poll and self.poll_begin and
                self.poll_begin <= now_ and
                (not self.poll_end or self.poll_end >= now_))


def choose_lecture_materials_filename(instance, original):
    extension = os.path.splitext(original)[1]
    lecture_slug = slugify(unicode(instance))[:74]
    return "%s/%s%s" % (instance.event.date.isoformat(),
                        lecture_slug, extension)


@python_2_unicode_compatible
class Lecture(models.Model):
    event = models.ForeignKey(Event, verbose_name="akcia",
                              related_name="lectures")
    lecturer = models.CharField(max_length=100, blank=True,
                                verbose_name="prednášajúci")
    title = models.CharField(max_length=147, verbose_name="názov prednášky")
    abstract = models.TextField(blank=True, verbose_name="abstrakt")
    room = models.CharField(max_length=20, verbose_name="miestnosť")
    time = models.TimeField(verbose_name="čas")
    field = models.CharField(max_length=47, blank=True,
                             verbose_name="odbor")
    video_url = models.URLField(blank=True, verbose_name="URL videa")
    materials = models.FileField(upload_to=choose_lecture_materials_filename,
                                 blank=True,
                                 verbose_name="materiály",
                                 help_text="Materiály od prednášajúceho, "
                                 "napr. slidy v PDF alebo ZIP obsahujúci "
                                 "všetky obrázky a videá.")
    poll = models.ForeignKey('polls.Poll', blank=True, null=True,
                             related_name="lectures",
                             help_text="Anketa")

    class Meta:
        verbose_name = "bod programu (napr. prednáška)"
        verbose_name_plural = "body programu (napr. prednášky)"
        ordering = ("event", "time")

    def __str__(self):
        return "%s: %s" % (self.lecturer, self.title)


def get_latest_event(request):
    """
    Returns the latest event relevant for the current site.
    """
    site = get_current_site(request)
    return Event.objects.filter(sites__id__exact=site.pk).order_by('-date')[0]


@python_2_unicode_compatible
class IndividualSignup(models.Model):
    event = models.ForeignKey(Event, verbose_name="akcia",
                              related_name="individual_signups")

events/forms.py
# coding: utf-8
from django import forms
from django.core.exceptions import ValidationError
from django.dispatch import receiver
from ksp_login.forms import BaseUserProfileForm

from events.models import (AdditionalUserDetails, IndividualSignup,
        IndividualOvernightSignup, SchoolSignup, get_latest_event,
        get_signup_model)


MIN_YEAR = 1900
MAX_YEAR = 3000
MAX_STUDENTS_PER_SCHOOL = 50


class AdditionalUserDetailsForm(BaseUserProfileForm):
    class Meta:
        model = AdditionalUserDetails
        exclude = ('user',)
        widgets = {
            'school': forms.Select(attrs={'class': 'autocomplete'}),
        }

    def clean_graduation(self):
        """
        If the user is a teacher, we allow this to be empty, otherwise
        require the user to provide a value between MIN_YEAR and MAX_YEAR.
        """
        if (self.cleaned_data['is_teacher'] and
                not self.cleaned_data['graduation']):
            return None
        if (not self.cleaned_data['graduation'] or not
                (MIN_YEAR <= self.cleaned_data['graduation'] <= MAX_YEAR)):
            raise forms.ValidationError("Treba zadať valídny rok maturity.")
        return self.cleaned_data['graduation']


class SignupFormMixin(object):
    is_plural = False

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        self.event = get_latest_event(request)
        self.user = request.user
        super(SignupFormMixin, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(SignupFormMixin, self).save(commit=False)
        if instance.event_id is None:
            instance.event = self.event
        if instance.user_id is None:
            instance.user = self.user
        if commit:
            instance.save()
        return instance


class IndividualOvernightSignupFormMixin(SignupFormMixin):
    def clean_sleeping_bag(self):
        if (self.cleaned_data['sleeping_bag'] and not
                self.cleaned_data['sleepover']):
            raise ValidationError("Spacák požičiame iba tým, ktorí "
                                  "prespávajú.")
        return self.cleaned_data['sleeping_bag']

    def clean_sleeping_pad(self):
        if (self.cleaned_data['sleeping_pad'] and not
                self.cleaned_data['sleepover']):
            raise ValidationError("Karimatku požičiame iba tým, ktorí "
                                  "prespávajú.")
        return self.cleaned_data['sleeping_pad']


class SchoolSignupFormMixin(SignupFormMixin):
    is_plural = True

    def clean(self):
        data = self.cleaned_data
        signed_up = sum(data.get('students%d' % (i,), 0) for i in range(1,5))
        if signed_up > MAX_STUDENTS_PER_SCHOOL:
            raise ValidationError("Z jednej školy povoľujeme najviac %d "
                                  "žiakov, %d zadaných." %
                                  (MAX_STUDENTS_PER_SCHOOL, signed_up))
        return super(SchoolSignupFormMixin, self).clean()


signup_form_mixins = {
    IndividualSignup: SignupFormMixin,
    IndividualOvernightSignup: IndividualOvernightSignupFormMixin,
    SchoolSignup: SchoolSignupFormMixin,
}


def get_signup_form(request):
    """
    Returns the appropriate signup form based on the result of
    get_signup_model.
    """
    model_class = get_signup_model(request)
    class SignupForm(signup_form_mixins[model_class], forms.ModelForm):
        class Meta:
            model = model_class
            exclude = ('user', 'event')

    return SignupForm

templates/events/event_archive.html
{% extends "base.html" %}

{% block title %}Archív{% endblock title %}

{% block content %}
  <ul>
    {% for event in event_list %}
      <li>
        <a href="{{ event.get_absolute_url }}">{{ event }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/events/event_attendance.html
{% extends "base.html" %}

{% block title %}Zoznam účastníkov: {{ event }}{% endblock title %}

{% block content_top_navigation %}
  <a href="{{ event.get_absolute_url }}">Naspäť na program</a>
{% endblock content_top_navigation %}

{% block content %}
  {% if school_signups %}
    <h2>Nahlásené školy</h2>
    <table>
      <thead>
        <tr>
          <th>Názov školy</th>
          <th>Mesto</th>
          <th>Počet žiakov</th>
          <th>Učiteľ</th>
        </tr>
      </thead>
      <tbody>
        {% for school in school_signups %}
          <tr>
            <td>{{ school.school.verbose_name }}</td>
            <td>{{ school.school.city }}</td>
            <td>{{ school.signup.get_total_students }}</td>
            <td>{{ school.teacher.get_full_name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
  <h2>Nahlásení jednotlivci</h2>
  <table>
    <thead>
      <tr>
        <th>Meno</th>
        <th>Škola</th>
        <th>Mesto</th>
        <th>Ročník</th>
      </tr>
    </thead>
    <tbody>
      {% for individual in individual_signups %}
        <tr>
          <td>{{ individual.user.get_full_name }}</td>
          <td>{{ individual.school.verbose_name }}</td>
          <td>{{ individual.school.city }}</td>
          <td>
            {% if individual.grade > 4 %}
              zmaturovaný
            {% else %}
              {{ individual.grade }}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Štatistiky</h2>
  <ul>
    <li>
      <span class="stats_label">Počet účastníkov:</span>
      <span class="stats_value">{{ signup_stats.total }}</span>
    </li>
    {% if signup_stats.grades %}
      <li>
        <span class="stats_label">Rozloženie na ročníky</span>
        <ul>
          {% for grade, count in signup_stats.grades %}
            <li>
              <span class="stats_label">{{ grade }}:</span>
              <span class="stats_value">{{ count }}</span>
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}
    <li>
      <span class="stats_label">Počet obedov:</span>
      <span class="stats_value">{{ signup_stats.lunches }}</span>
    </li>
    {% if signup_stats.overnight %}
    <li>
      <span class="stats_label">Počet prespávajúcich:</span>
      <span class="stats_value">{{ signup_stats.oversleeping }}</span>
    </li>
    <li>
      <span class="stats_label">Počet spacákov:</span>
      <span class="stats_value">{{ signup_stats.sleeping_bags }}</span>
    </li>
    <li>
      <span class="stats_label">Počet karimatiek:</span>
      <span class="stats_value">{{ signup_stats.sleeping_pads }}</span>
    </li>
    <li>
      <span class="stats_label">Počet záujemcov o&nbsp;hru:</span>
      <span class="stats_value">{{ signup_stats.game_participants }}</span>
    </li>
    {% endif %}
  </ul>
  {% if site.domain == "akademia.trojsten.sk" %}
    <p>
      Ak niekomu vŕta v&nbsp;hlave, prečo sa čísla nezhodujú
      s&nbsp;tabuľkami, je to preto, že do celkového počtu účastníkov
      počítame aj učiteľov a&nbsp;do štatistík nepočítame tých jednotlivcov,
      ktorých školy už majú spravené hromadné registrácie.
    </p>
  {% endif %}
{% endblock content %}

templates/events/event_detail.html
{% extends "base.html" %}

{% block title %}Program: {{ event }}{% endblock title %}

{% block content_top_navigation %}
  {% if do_signups %}
    <a href="#signup">Nahlásenie účasti</a> |
  {% endif %}
  <a href="{{ event.get_attendance_url }}">Zoznam nahlásených účastníkov</a>
{% endblock content_top_navigation %}

{% block content %}
  <h4>Dátum konania: {{ event.date|date:"j. n. Y" }}</h4>
  {% if event.get_grouped_lectures %}
    <ul class="event_schedule">
      {% for time, lectures in event.get_grouped_lectures.items %}
        <li><span class="lecture_time">{{ time|time:"H:i" }}</span>
          <ul>
            {% for lecture in lectures %}
              <li>
                {% if lecture.lecturer %}
                  <span class="lecturer">{{ lecture.lecturer }}</span> –
                {% endif %}
                <span class="lecture_title">{{ lecture.title }}</span>
                <span class="lecture_room">(Miestnosť {{ lecture.room }})</span>
                {% if lecture.video_url or lecture.materials %}
                  <div class="lecture_resource">
                    {% if lecture.video_url %}
                      <a href="{{ lecture.video_url }}">Záznam prednášky</a>
                    {% endif %}
                    {% if lecture.materials %}
                      <a href="{{ lecture.materials.url }}">Prezentácia</a>
                    {% endif %}
                  </div>
                {% endif %}
                {% if lecture.field %}
                  <p class="lecture_field">Odbor: {{ lecture.field }}</p>
                {% endif %}
                <p class="lecture_abstract">
                  {{ lecture.abstract }}
                </p>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Pre túto akciu ešte nemáme program...</p>
  {% endif %}
  {% if do_signups %}
    <a id="signup"></a>
    {% if event.signup_period_open %}{% with deadline=event.deadline|date:"j. n. Y, H:i" %}
      {% if is_signed_up %}
        <h2>Zmena prihlášky na akciu</h2>
        <p>Prihlášky sa dajú meniť do {{ deadline }}.</p>
      {% else %}
        <h2>Prihlásenie na akciu</h2>
        <p>Prihlasovať sa dá do {{ deadline }}.</p>
      {% endif %}
      {% if user.is_authenticated %}
        <form action="" method="post">
          {% csrf_token %}
          <table>
            {{ signup_form }}
            <tr class="form_buttons">
              <td />
              <td>
                  <input type="submit" value="Odoslať" />
              </td>
            </tr>
          </table>
        </form>
        {% if is_signed_up %}
          <h2>Odhlásenie z&nbsp;akcie</h2>
          <p>Odhlasovať sa dá do {{ deadline }}.</p>
          <form action="" method="post">
            {% csrf_token %}
            <table>
              <tr>
                <th />
                <td>
                  <input type="submit" name="sign_out" value="Neprídem{% if signup_form.is_plural %}e{% endif %}" />
                </td>
              </tr>
            </table>
          </form>
        {% endif %}
      {% else %}
        <p>
          Najprv sa treba <a href="{% url "account_login" %}">prihlásiť na
          stránku</a>.
        </p>
      {% endif %}
    {% endwith %}{% else %}
      <p>Prihlasovanie na túto akciu už bolo uzavreté.</p>
    {% endif %}
  {% endif %}
{% endblock content %}

templates/events/event_poll.html
{% extends "base.html" %}

{% block title %}Anketa: {{ event }}{% endblock title %}

{% block content_top_navigation %}
  <a href="{{ event.get_absolute_url }}">Naspäť na program</a>
{% endblock content_top_navigation %}

{% block content %}
  {% if event.poll_is_active %}
    <form action="" method="POST">
      {% csrf_token %}
      {% for group_title, group in polls %}
        <h2>{{ group_title }}</h2>
        {% for question, form in group %}
          <div class="poll_question">
            <p>
              {{ question }}
            </p>
            <div class="poll_answer">
              {{ form.value.errors }}
              {{ form.value }}
            </div>
          </div>
        {% endfor %}
      {% endfor %}
      <p>
        <input type="submit" value="Odoslať" />
      </p>
    </form>
  {% else %}
    <p>Anketa pre akciu {{ event }} momentálne nebeží.
  {% endif %}
{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script src="{{ STATIC_URL }}js/stars.js"></script>
{% endblock scripts %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/stars.css" type="text/css" />
{% endblock head %}

templates/events/event_poll_results.html
{% extends "base.html" %}

{% block title %}Výsledky ankety: {{ event }}{% endblock title %}

{% block content_top_navigation %}
  <a href="{{ event.get_absolute_url }}">Naspäť na program</a>
{% endblock content_top_navigation %}

{% block content %}
  {% for group_title, group in polls %}
    <h2>{{ group_title }}</h2>
    {% for question in group %}
      <div class="poll_question">
        <p>
          {{ question.question }}
        </p>
        {% if question.answers %}
          {% for answer in question.answers %}
            <div class="poll_answer_text">
              <div class="poll_answer_header" id="answer_{{ answer.id }}">
                <a href="#answer_{{ answer.id }}">#{{ answer.id }}</a>:
              </div>
              {{ answer.render_text }}
            </div>
          {% endfor %}
        {% elif question.options %}
          <table class="poll_options_result">
            <thead>
              <tr>
                <td>Možnosť</td>
                <td>Počet hlasov</td>
              </tr>
            </thead>
            <tbody>
              {% for option in question.options %}
                <tr>
                  {% for cell in option %}
                    <td>{{ cell }}</td>
                  {% endfor %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <div class="poll_answers_none">
            <p>Túto otázku nikto nezodpovedal.</p>
          </div>
        {% endif %}
      </div>
    {% endfor %}
  {% endfor %}
{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <script src="{{ STATIC_URL }}js/choice_distributions.js"></script>
{% endblock scripts %}